apiVersion: v1
kind: Service
metadata:
  name: { { .Release.Name } }
spec:
  selector:
    app.kubernetes.io/name: x424-verifier
    app.kubernetes.io/instance: { { .Release.Name } }
  ports:
    - name: http
      port: { { .Values.service.port } }
      targetPort: http
